name: GitHub Actions Events Demo

on:
  repository_dispatch:
    types: [test_result]
  pull_request:
    types: [opened]

jobs:
  Get-Environment-Variables:
    runs-on: ubuntu-latest
    steps:
      - name: Read environment variables
        run: |
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "GITHUB SHA: ${{ github.sha }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
      
      - name: Parsing client payload message
        run: |
          echo $MESSAGE
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
        
